monster_data = {
    "1": [
        "Awakened Shrub",
        "Baboon",
        "Badger",
        "Bat",
        "Cat",
        "Commoner",
        "Crab",
        "Deer",
        "Eagle",
        "Frog",
        "Giant Fire Beetle",
        "Goat",
        "Hawk",
        "Homunculus",
        "Hyena",
        "Jackal",
        "Lemure",
        "Lizard",
        "Octopus",
        "Owl",
        "Quipper",
        "Rat",
        "Raven",
        "Scorpion",
        "Sea Horse",
        "Shrieker",
        "Spider",
        "Vulture",
        "Weasel"
    ],
    "2": [
        "Bandit",
        "Blood Hawk",
        "Camel",
        "Cultist",
        "Flying Snake",
        "Giant Crab",
        "Giant Rat",
        "Giant Weasel",
        "Guard",
        "Kobold",
        "Mastiff",
        "Merfolk",
        "Mule",
        "Noble",
        "Poisonous Snake",
        "Pony",
        "Stirge",
        "Tribal Warrior"
    ],
    "3": [
        "Acolyte",
        "Axe Beak",
        "Blink Dog",
        "Boar",
        "Constrictor Snake",
        "Draft Horse",
        "Dretch",
        "Elf, Drow",
        "Elk",
        "Flying Sword",
        "Giant Badger",
        "Giant Bat",
        "Giant Centipede",
        "Giant Frog",
        "Giant Lizard",
        "Giant Owl",
        "Giant Poisonous Snake",
        "Giant Wolf Spider",
        "Goblin",
        "Grimlock",
        "Panther",
        "Pseudodragon",
        "Riding Horse",
        "Skeleton",
        "Sprite",
        "Steam Mephit",
        "Swarm of Bats",
        "Swarm of Rats",
        "Swarm of Ravens",
        "Violet Fungus",
        "Wolf",
        "Zombie"
    ],
    "4": [
        "Ape",
        "Black bear",
        "Cockatrice",
        "Crocodile",
        "Darkmantle",
        "Dust Mephit",
        "Giant Goat",
        "Giant Sea Horse",
        "Giant Wasp",
        "Gnoll",
        "Gnome, Deep (Svirfneblin)",
        "Gray Ooze",
        "Hobgoblin",
        "Ice Mephit",
        "Lizardfolk",
        "Magma Mephit",
        "Magmin",
        "Orc",
        "Reef Shark",
        "Rust Monster",
        "Sahuagin",
        "Satyr",
        "Scout",
        "Shadow",
        "Swarm of Insects",
        "Thug",
        "Warhorse",
        "Warhorse Skeleton",
        "Worg"
    ],
    "5": [
        "Animated Armor",
        "Brass Dragon Wyrmling",
        "Brown Bear",
        "Bugbear",
        "Copper Dragon Wyrmling",
        "Death Dog",
        "Dire Wolf",
        "Dryad",
        "Duergar",
        "Ghoul",
        "Giant Eagle",
        "Giant Hyena",
        "Giant Octopus",
        "Giant Spider",
        "Giant Toad",
        "Giant Vulture",
        "Harpy",
        "Hippogriff",
        "Imp",
        "Lion",
        "Quasit",
        "Specter",
        "Spy",
        "Swarm of Quippers",
        "Tiger"
    ],
    "6": [
        "Ankheg",
        "Awakened Tree",
        "Azer",
        "Bandit Captain",
        "Berserker",
        "Black Dragon Wyrmling",
        "Bronze Dragon Wyrmling",
        "Centaur",
        "Cult Fanatic",
        "Druid",
        "Ettercap",
        "Gargoyle",
        "Gelatinous Cube",
        "Ghast",
        "Giant Boar",
        "Giant Constrictor Snake",
        "Giant Elk",
        "Gibbering Mouther",
        "Green Dragon Wyrmling",
        "Grick",
        "Griffon",
        "Hunter Shark",
        "Merrow",
        "Mimic",
        "Minotaur Skeleton",
        "Ochre Jelly",
        "Ogre",
        "Ogre Zombie",
        "Pegasus",
        "Plesiosaurus",
        "Polar Bear",
        "Priest",
        "Rhinoceros",
        "Rug of Smothering",
        "Saber-Toothed Tiger",
        "Sea Hag",
        "Silver Dragon Wyrmling",
        "Swarm of Poisonous Snakes",
        "Wererat",
        "White Dragon Wyrmling",
        "Will-o'-Wisp"
    ],
    "7": [
        "Basilisk",
        "Bearded Devil",
        "Blue Dragon Wyrmling",
        "Doppelganger",
        "Giant Scorpion",
        "Gold Dragon Wyrmling",
        "Green Hag",
        "Hell Hound",
        "Killer Whale",
        "Knight",
        "Manticore",
        "Minotaur",
        "Mummy",
        "Nightmare",
        "Owlbear",
        "Phase Spider",
        "Veteran",
        "Werewolf",
        "Wight",
        "Winter Wolf"
    ],
    "8": [
        "Black Pudding",
        "Chuul",
        "Couatl",
        "Elephant",
        "Ettin",
        "Ghost",
        "Lamia",
        "Red Dragon Wyrmling",
        "Succubus/Incubus",
        "Wereboar",
        "Weretiger"
    ],
    "9": [
        "Air Elemental",
        "Barbed Devil",
        "Bulette",
        "Earth Elemental",
        "Fire Elemental",
        "Flesh Golem",
        "Giant Crocodile",
        "Giant Shark",
        "Gladiator",
        "Gorgon",
        "Half-Red Dragon Veteran",
        "Hill Giant",
        "Night Hag",
        "Otyugh",
        "Roper",
        "Salamander",
        "Shambling Mound",
        "Triceratops",
        "Troll",
        "Unicorn",
        "Vampire Spawn",
        "Water Elemental",
        "Werebear",
        "Wraith",
        "Xorn"
    ],
    "10": [
        "Chimera",
        "Drider",
        "Invisible Stalker",
        "Mage",
        "Mammoth",
        "Medusa",
        "Vrock",
        "Wyvern"
    ],
    "11": [
        "Giant Ape",
        "Oni",
        "Shield Guardian",
        "Stone Giant"
    ],
    "12": [
        "Assassin",
        "Chain Devil",
        "Cloaker",
        "Frost Giant",
        "Hezrou",
        "Hydra",
        "Spirit Naga",
        "Tyrannosaurus Rex"
    ],
    "13": [
        "Bone Devil",
        "Clay Golem",
        "Cloud Giant",
        "Fire Giant",
        "Glabrezu",
        "Treant"
    ],
    "14": [
        "Aboleth",
        "Deva",
        "Guardian Naga",
        "Stone Golem"
    ],
    "15": [
        "Behir",
        "Djinni",
        "Efreeti",
        "Gynosphinx",
        "Horned Devil",
        "Remorhaz",
        "Roc"
    ],
    "16": [
        "Archmage",
        "Erinyes"
    ],
    "17": [
        "Adult Brass Dragon",
        "Adult White Dragon",
        "Nalfeshnee",
        "Rakshasa",
        "Storm Giant",
        "Vampire"
    ],
    "18": [
        "Adult Black Dragon",
        "Adult Copper Dragon",
        "Ice Devil"
    ],
    "19": [
        "Adult Bronze Dragon",
        "Adult Green Dragon",
        "Mummy Lord",
        "Purple Worm"
    ],
    "20": [
        "Adult Blue Dragon",
        "Adult Silver Dragon",
        "Iron Golem",
        "Marilith",
        "Planetar"
    ],
    "21": [
        "Adult Gold Dragon",
        "Adult Red Dragon",
        "Androsphinx",
        "Dragon Turtle"
    ],
    "22": [
        "Balor"
    ],
    "23": [
        "Pit Fiend"
    ],
    "24": [
        "Lich",
        "Solar"
    ],
    "25": [
        "Kraken"
    ],
    "26": [
        "Tarrasque"
    ]
}
